replicaCount: 1
image:
  repository: managed-by-azuredevops
  tag: managed-by-azuredevops
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-secret
nameOverride: "xxx"
fullnameOverride: "xxx"
serviceAccount:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  type: ClusterIP
  port: 80 
  targetPort: 8080 
  livenessProbe:
    enabled: false
    path: "/"
    port: http
  readinessProbe:
    enabled: false
    path: "/"
    port: http

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: xxx.xxx.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
tolerations: []
affinity: {}

extraSecret:
  name: xxx-extra-secret
  data:
    ConnectionStrings__XX: "aa"