{{- if .Values.externalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  {{- if .Values.externalSecret.namespace }}
  namespace: {{ .Values.externalSecret.namespace }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "5m" }}

  {{- if .Values.externalSecret.generatorName }}

  #  Dynamic Database Mode
  target:
    name: {{ .Values.externalSecret.target.name | default .Values.externalSecret.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: {{ .Values.externalSecret.generatorName }}

  {{- else }}

  # 🔹 KV Mode
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}

  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}

  data:
  {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}

  {{- end }}
{{- end }}
