{{- if .Values.externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.target.name | default .Values.externalSecret.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}

  {{- if .Values.externalSecret.data }}
  data:
  {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
  {{- else }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.name }}
  {{- end }}
{{- end }}
